apiVersion: v1
kind: Config
users:
- name: <USER_NAME>
  user:
    token: <TOKEN>
clusters:
- cluster:
    certificate-authority-data: <CERTIFICATE_AUTHORITY_DATA>
    server: <CLUSTER_ENDPOINT>
  name: <CLUSTER_NAME>
contexts:
- context:
    cluster: <CLUSTER_NAME>
    namespace: <NAMESPACE>
    user: <USER_NAME>
  name: <NAMESPACE>
current-context: <NAMESPACE>
